openapi: "3.0.0"
info:
  version: 1.0.0
  title: NAB Service
  description: A service to store your contacts
paths:
  /api/contacts:
    get:
      description: |
        Returns all contacts
      operationId: all contacts
      responses:
        '200':
          description: Return all contacts stored in the book
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
        "404":
          description: Any error will return to 404
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/contacts/submit:
    post:
      description: Submit a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "200":
          description: Successful handling.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "404":
          description: Any error will return to 404
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
      - error
      properties:
        error:
          type: string
          
    Message:
      type: object
      required:
      - message
      properties:
        message:
          type: string
    Contact:
      type: object
      required:
      - name
      properties:
        id:
          type: string
        name:
          type: string
        phone:
          type: string
        address:
          type: string
        email:
          type: string
      
